### ISSUE TITLE
Add Photo Gallery section to the web page.

### ISSUE THREAD

**Issue by Mahak008** [RIKI-05/MOMOMIA#101]

**Comment by RIKI-05** [comment]
umm Idk how it will look :/

**Comment by amitroy-thedev** [comment]
hey @RIKI-05 the cart ui/ux issue closed would you open it again

**Comment by amitroy-thedev** [comment]
before merging other pull request please merge mine one i've done the work twice

**Comment by RIKI-05** [comment]
@amitroy-thedev the issue and the pr both are open ...please do the necessary changes

**Comment by Mahak008** [comment]
Hi,
Can I send you some sample images on mail ?

**Comment by RIKI-05** [comment]
@Mahak008 Please look for some other issue ...i guess this won't look good
