### ISSUE TITLE
Change the fonts of Momomia in the navbar.

### ISSUE THREAD

**Issue by idraksheikh** [RIKI-05/MOMOMIA#112]
change the font-family of Momomia in the navbar if you permit.

**Before changing:**

![image](https://user-images.githubusercontent.com/60965415/194899757-d02357e7-ca70-4e21-819e-2d994ecfd9af.png)

**After changing:**

![image](https://user-images.githubusercontent.com/60965415/194900158-89ec0951-4e50-432b-bc66-086afde6925d.png)

**Comment by RIKI-05** [comment]
@idraksheikh it looks nice ...do the same for momomia text on the footer

**Comment by idraksheikh** [comment]
Ok @RIKI-05

**Comment by rishissahu** [comment]
I would like to change the font of Momomia.
