### ISSUE TITLE
Change the color of the Cart Text area to white and font to black

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#129]
![2022-10-11 (1)](https://user-images.githubusercontent.com/62802231/195008932-9907262b-5bc2-421f-ac0c-a1e165a6eae8.png)

**Comment by syprogrammer** [comment]
can you assign me

**Comment by RIKI-05** [comment]
yes sure

**Comment by syprogrammer** [comment]
@RIKI-05 i have made changes now it look like this check it : https://bit.ly/3TaFcou

**Comment by RIKI-05** [comment]
@syprogrammer make the PR it looks good
