### ISSUE TITLE
Changing Color of Navbar Items 

### ISSUE THREAD

**Issue by Swap-nil-2003** [RIKI-05/MOMOMIA#131]
The colour of Navbar Items - Home, Category etc is not visible against the background. I would like to change that.

**Comment by RIKI-05** [comment]
![2022-10-11](https://user-images.githubusercontent.com/62802231/195026272-b0156d18-8f54-4a90-91a1-dfc245593743.png)


@Swap-nil-2003 ....the navbar is quite good and clear can you explain to me about what changes are you talking about

**Comment by Swap-nil-2003** [comment]
![Screenshot_20221011-134952](https://user-images.githubusercontent.com/93329536/195037168-84669776-54a5-4235-adf6-e9815e777100.jpg)
In the mobile version, the Navbar Items are not visible clearly due to the background.

**Comment by RIKI-05** [comment]
@Swap-nil-2003  Oh ohkay it would be great if you can work on it 😄

**Comment by maneet057** [comment]
Can I please do it under Hacktoberfest tag??
