### ISSUE TITLE
create a contact page 

### ISSUE THREAD

**Issue by ShravaniAK** [RIKI-05/MOMOMIA#133]

**Comment by ShravaniAK** [comment]
pl assign me this issue

**Comment by RIKI-05** [comment]
@ShravaniAK we already have a contact page .... if you can just add the navbar to it (present in the index.html) that would be a great help

**Comment by Aman1143** [comment]
hii @RIKI-05  I want to add navbar on the contact page . pls assign it to me

**Comment by Anukool1729** [comment]
Hi please assign me this issue, I would like to  work on this.
