### ISSUE TITLE
Adding footer to Terms and services page

### ISSUE THREAD

**Issue by AvadhootK** [RIKI-05/MOMOMIA#139]
Hey @RIKI-05 ,
I would like to add the footer to terms and services page which will be the same as home page.
Also, there is no way of navigating back to the home page from the terms and services page as well as the contact page.
I would like to include a link to home page besides the other links in the footer.

![Screenshot (678)](https://user-images.githubusercontent.com/72447002/195052193-db7f1932-5cbc-4116-b3bf-bd7a424b5034.png)

**Comment by DhirajGilda** [comment]
is this issue assigned @AvadhootK

**Comment by DhirajGilda** [comment]
i would like to work on this

**Comment by RIKI-05** [comment]
@AvadhootK sorry for the delay please do the necessary changes

**Comment by RIKI-05** [comment]
@DhirajGilda if you want you can make a dummy policies page
