### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by dharmikjethva30** [RIKI-05/MOMOMIA#145]
Improve of how price of itemis shown. Appropriate spacing is not given. Also can add Rupee symbol to it
![image](https://user-images.githubusercontent.com/97388367/195102343-5ba3a66e-7641-4e26-a1ea-3b5556285935.png)

**Comment by RIKI-05** [comment]
@dharmikjethva30 please do the necessary changes

**Comment by ImanHasan** [comment]
I would like to on that please assign this to me
