### ISSUE TITLE
Make the page responsive for smartphone widths

### ISSUE THREAD

**Issue by ena-04** [RIKI-05/MOMOMIA#154]
i would like to work on this, please assign it to me

**Comment by RIKI-05** [comment]
@ena-04 the project is working fine for the smartphone width can you point out the issues you are referring to

**Comment by RIKI-05** [comment]
@ena-04 ohkay you can work on the issue

**Comment by ena-04** [comment]
@RIKI-05 i have modified it and created a pr, please check.
