### ISSUE TITLE
Add navbar to the terms and condition page

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#155]
Nav bar should look exactly like the one in index.html

**Comment by AvadhootK** [comment]
Hey @RIKI-05 , can I work on this?

**Comment by VineethKumarM** [comment]
Can i work on this?

**Comment by ayobamiseun** [comment]
can i work on this

**Comment by RohitSaklani** [comment]
i would like to contribute on this  . 
can you assign me ?

**Comment by RIKI-05** [comment]
With so many competitors it's 

> "Whoever does it first "

😅

**Comment by ena-04** [comment]
@RIKI-05  i have modified it and created a pr, please check.

**Comment by Arka009chakraborty** [comment]
I want to work in this .
Can I work?

**Comment by aankitasoni** [comment]
I would like to work on this repository, would you please assign this to me. @RIKI-05

**Comment by maneet057** [comment]
Can I please do it under Hacktoberfest tag??
