### ISSUE TITLE
Change the Font and font-size of MOMOMIA on the navbar ROBOTO

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#17]

**Comment by ShishuSidharth** [comment]
Can you please assign this to me. I want to work on this

**Comment by RIKI-05** [comment]
Sure Go ahead @ShishuSidharth

**Comment by ShishuSidharth** [comment]
Thanks @RIKI-05

**Comment by ShishuSidharth** [comment]
![Screenshot 2022-10-09 152305](https://user-images.githubusercontent.com/87175803/194750180-5bc92991-e72c-4fe7-a50f-cd4cca46fe45.jpg)
 

is this alright?

**Comment by priyanshusingh305** [comment]
please assign me this issue

**Comment by archit2216** [comment]
Hi @RIKI-05 I have changed the font and font size same as given in screenshots, please merge this PR under the label-hacktoberfest-accepted
