### ISSUE TITLE
Change the hover color of the footer clickables to #ffc107

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#18]

**Comment by jsvigneshkanna** [comment]
I would like work on this please assign to my name

**Comment by prerit2001** [comment]
I would love to contribute on this.

**Comment by rahul8858** [comment]
I want to contribute. Please assign this issue to me.

**Comment by Gumanpratapsingh** [comment]
I want to work upon this issue. Please assign the issue to me.
Thanks

**Comment by jsvigneshkanna** [comment]
PR: #26 
@RIKI-05

**Comment by AditiBendre** [comment]
Hii
Can i work on this issue?

**Comment by piyushkdas0611** [comment]
i would like to work on this
