### ISSUE TITLE
Add chat with whatsapp feature

### ISSUE THREAD

**Issue by zugzwang03** [RIKI-05/MOMOMIA#182]
I want to add the "chat with whatsapp" feature for placing the order by the user.
I can add a dummy number, that can add a realistic view to the website, later if you get any valid number, you can add that in.
Also, there are certain link fixes that needs to be done in the website, I can work on that as well simultaneously.
Can I contribute it under Hacktoberfest'22?

![whatapp](https://user-images.githubusercontent.com/95460021/196032646-a9e7fc8d-84c7-4b54-b4ae-714b385419db.png)

**Comment by RIKI-05** [comment]
@zugzwang03 this feature already exists in the present design ...try placing an order 😉
