### ISSUE TITLE
No need of Contact us link in the Contact.html page

### ISSUE THREAD

**Issue by devwithsubhrajit2002** [RIKI-05/MOMOMIA#185]
There is no need for the contact us link below in the contact us.html itself. Why should I click the contact link again as I already entered the page?
@RIKI-05 please assign me the task of removing this link in the contact us.html page under the Hactoberfest tag.
![new issue in momo](https://user-images.githubusercontent.com/108873732/196126801-84e2da49-bd34-42b2-b502-54e51defdc7c.png)

**Comment by RIKI-05** [comment]
@devwithsubhrajit2002 just remove the contact us link from the footer
