### ISSUE TITLE
Improve the styling of the headings

### ISSUE THREAD

**Issue by mchirag2002** [RIKI-05/MOMOMIA#188]
I would like to change the style of the headings in the Categories and Hygiene sections
![image](https://user-images.githubusercontent.com/71757438/196363867-f1fffbf9-3c47-4d20-bb0c-83f80eb58272.png)
![image](https://user-images.githubusercontent.com/71757438/196364042-faf90b59-896e-481a-8e56-b9bf23d6378a.png)

And change them to - 
![image](https://user-images.githubusercontent.com/71757438/196364111-6c0c7ec1-08f3-4fd5-9083-cba43ed63343.png)
![image](https://user-images.githubusercontent.com/71757438/196364147-1d7c02db-dca3-4abc-8721-a75c079bee3c.png)

**Comment by mchirag2002** [comment]
@RIKI-05 Please assign this issue to me under the Hacktoberfest tag.

**Comment by chaotic-10** [comment]
@RIKI-05  I'm able to solve this issue, so if you  could assign me this task, under the Hacktoberfest tag.

**Comment by maneet057** [comment]
Can I please do it under Hacktoberfest tag??

**Comment by habeebputhiyakath** [comment]
i'm ready to Improve the styling of the headings
Please assign  me this issue 
 the Hacktoberfest tag.

**Comment by RIKI-05** [comment]
@mchirag2002 the change isn't required
