### ISSUE TITLE
change the contact US page header style to the same as the home page header style 

### ISSUE THREAD

**Issue by habeebputhiyakath** [RIKI-05/MOMOMIA#189]
change the contact US page header style to the same as the home page header style 

I'm able to solve this issue, so if you could assign me this task, under the Hacktoberfest tag.

![Contact US and 3 more pages - Personal - Microsoft​ Edge 18-10-2022 17_40_00](https://user-images.githubusercontent.com/110285678/196440106-8a2fe297-980b-4071-969d-e2e66ea4fdbe.png)
![Contact US ](https://user-images.githubusercontent.com/110285678/196440202-aebb90a5-1ca8-41db-b6d0-2a8eebcd7ca5.png)

And change them to -

![Contact US changes](https://user-images.githubusercontent.com/110285678/196444245-5e08e20f-e493-4e90-9f9c-adba46efda18.png)

**Comment by RIKI-05** [comment]
@habeebputhiyakath sorry this issue has already been solved

**Comment by habeebputhiyakath** [comment]
> @habeebputhiyakath sorry this issue has already been solved

ok
