### ISSUE TITLE
minor loading problem was detected

### ISSUE THREAD

**Issue by habeebputhiyakath** [RIKI-05/MOMOMIA#191]
A minor loading problem was detected
![MOMOMIA and 5 more pages - Personal - Microsoft​ Edge 18-10-2022 17_35_17](https://user-images.githubusercontent.com/110285678/196465220-0d39d11a-bb28-4ca6-9c94-bb94280cb772.png)

**Comment by RIKI-05** [comment]
@habeebputhiyakath can you explain more about the issue..
