### ISSUE TITLE
UI of the send message box can be changed to make it match with the background 

### ISSUE THREAD

**Issue by maneet057** [RIKI-05/MOMOMIA#192]
![image](https://user-images.githubusercontent.com/77922626/196464666-f1e93b86-e1fc-4d4e-82c7-e77d3319b981.png)
This box's color and a bit of shape can be changed to make it look more attractive and pleasing.

Please assign me this issue under hacktoberfest.

**Comment by RIKI-05** [comment]
@maneet057 go ahead with the changes

**Comment by maneet057** [comment]
Ok thank you!
