### ISSUE TITLE
Improving the readme.md file

### ISSUE THREAD

**Issue by Vanshiii203** [RIKI-05/MOMOMIA#195]

**Comment by Aman1143** [comment]
I want to improve readme.md file . assign it me

**Comment by RIKI-05** [comment]
@Vanshiii203  you can work on it

**Comment by Aman1143** [comment]
Hii @RIKI-05  What type of changes you want to see ??
If you tell me this . Defiantly it help me to improve readme.md file.

**Comment by Sidkul2000** [comment]
Hi @RIKI-05 ! I am ready to make changes as required in the readme.md file. Could you please assign this task to me?
