### ISSUE TITLE
Homepage image is not proper 

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#2]

**Comment by VidishaAG** [comment]
I can work on this. Please tell me what kind of image you want and where.

**Comment by RIKI-05** [comment]
@VidishaAG  As you must have seen the homepage image is getting cut. I want an attractive momo platter without any background to be replaced with the present image
![2022-10-09](https://user-images.githubusercontent.com/62802231/194744718-ee11f19d-7004-4385-ba60-b0d9f6d7a8ee.png)


Can you do this?

**Comment by hritesh94** [comment]
Hi can you assign me this issue i think i can work on it

**Comment by RIKI-05** [comment]
@hritesh94 you too can work on this

**Comment by VidishaAG** [comment]
@RIKI-05 I am unassigning myself from this. I can work on the documentation of style.css . Please assign me that issue

**Comment by RIKI-05** [comment]
@VidishaAG sure

**Comment by hritesh94** [comment]
![momomia_updated](https://user-images.githubusercontent.com/89804314/194753924-8ecd0287-fa32-42b6-9896-dbbc78fd43f0.jpg)


Does this looks good? ,as per your comment i thought you wanted a new image,

**Comment by RIKI-05** [comment]
@hritesh94  this looks good but you see from right side this image is also getting cut

**Comment by RIKI-05** [comment]
![53281477](https://user-images.githubusercontent.com/62802231/194762369-e28e02a3-533b-4ec8-94a1-6764d650297a.jpg)


@hritesh94 try using this remove the background and upload the image

**Comment by hritesh94** [comment]
![image](https://user-images.githubusercontent.com/89804314/194764870-1aef9e2c-8f33-4d66-853c-7da7bafab223.png)

Is this okay ?

**Comment by ansharora28** [comment]
@RIKI-05 can i update the readme file once with the proper screenshot once this PR is accepted?

**Comment by RIKI-05** [comment]
> @RIKI-05 can i update the readme file once with the proper screenshot once this PR is accepted?

Yes Please go Ahead @ansharora28

**Comment by hritesh94** [comment]
> ![image](https://user-images.githubusercontent.com/89804314/194764870-1aef9e2c-8f33-4d66-853c-7da7bafab223.png)
> 
> 
> @RIKI-05  Is this okay? 

@RIKI-05 Can you see the screenshot? Or should i change something?
