### ISSUE TITLE
Removal of Know More button in Hygiene section which is of no use

### ISSUE THREAD

**Issue by devwithsubhrajit2002** [RIKI-05/MOMOMIA#205]
The know more button opens the foodcourt app through which Foods are orderd. So if customers click that they would leave the MOMOMIA website and order on that Foodcourt website. How hygeine is linked to Foodcourt app or website. So i would suggest to remove the Know more button since what is having is enough for customers or change the link to appropriate Hygiene website.
@RIKI-05 please assign me this task under Hactoberfest tag so that I remove this uncertainty.
![hygiene prob](https://user-images.githubusercontent.com/108873732/197205104-e94c991b-702f-411e-8524-b006d72bf4ef.png)

**Comment by devwithsubhrajit2002** [comment]
@RIKI-05 please look into this and assign me this task under Hactoberfest tag.

**Comment by RIKI-05** [comment]
@devwithsubhrajit2002 I don't intent to remove the know more button if you want you can replace the link with some other relevant link

**Comment by devwithsubhrajit2002** [comment]
@RIKI-05 I will like to replace that with a relevant link
Ok assign me . I will complete this within today.
