### ISSUE TITLE
Making menu aligned at proper position/

### ISSUE THREAD

**Issue by Pallavibahekar** [RIKI-05/MOMOMIA#206]
As it is not looking good,
![2022-10-22 (1)](https://user-images.githubusercontent.com/97456579/197317450-41c6d704-679e-4395-b30b-b5a6398e5d8f.png)
I want to make it proper.
Could you please assign me this issue under hacktoberfest2022?

**Comment by RIKI-05** [comment]
@Pallavibahekar plz do the necessary changes
