### ISSUE TITLE
Fix the footer of the contact page

### ISSUE THREAD

**Issue by zugzwang03** [RIKI-05/MOMOMIA#211]
For mobile devices, the footer of the contacts page contains the social media icons overlapping with the name of the website. Possibly, if we can decrease the font size to some extent, it will fit well. Can I work on this issue under hacktoberfest'22?

![Screenshot_20221023-115137_Chrome](https://user-images.githubusercontent.com/95460021/197377368-c3aac53e-5491-4780-b225-bf345318057c.jpg)

**Comment by RIKI-05** [comment]
@zugzwang03  you can work on it

**Comment by zugzwang03** [comment]
Hey @RIKI-05, while I pulled all the files to work on this issue, I just discovered that some PR destroyed the whole mobile view of that page :(
![destroy](https://user-images.githubusercontent.com/95460021/198843741-0af76aec-e613-4fba-9c08-d7576158ede4.png)

**Comment by logicalahara** [comment]
@zugzwang03, would love to contribute to this. Please assign it to me
