### ISSUE TITLE
making the navbar of contact us page responsive

### ISSUE THREAD

**Issue by Vanshiii203** [RIKI-05/MOMOMIA#212]
![Screenshot (495)](https://user-images.githubusercontent.com/94471189/197377680-d942107b-41f4-40b6-8460-4c91e6154a21.png)

**Comment by m-mishra2001** [comment]
can you please assign me this issue @RIKI-05

**Comment by RIKI-05** [comment]
@Vanshiii203 you can work on the issue

**Comment by Vanshiii203** [comment]
@RIKI-05 some PR destroyed the whole mobile view of contact us  page
