### ISSUE TITLE
Cart Icon should be on the navbar for better user experience

### ISSUE THREAD

**Issue by ankitbajpai65** [RIKI-05/MOMOMIA#216]
Hello, while I was going through the website, I saw that the cart icon comes when we click any of the dish but when the user goes to add the variants of that dishes the cart icons goes up and not present in the viewable height so I think that the cart page icon should be on the navbar as it is sticky so the user will able to see the items he/she is adding. Please assign me this issue so that I can work on the same. Also let me know what you think of this.
Attaching image for reference:
![image](https://user-images.githubusercontent.com/85179394/198709219-0e2eed1f-de37-481f-bbb1-b2c771535c21.png)
image 1(The icon which I want to add to the navbar section)
![image](https://user-images.githubusercontent.com/85179394/198709495-ccad3a1b-349f-4c1b-94bd-0beefce06bb9.png)
image 2 (icon not showing and the user have to scroll to see the icon)
Thanks!

**Comment by RIKI-05** [comment]
@ankitbajpai65  you can work on this issue
