### ISSUE TITLE
Add smooth hover effect on icons

### ISSUE THREAD

**Issue by AnshuPathak-88825** [RIKI-05/MOMOMIA#221]
![image](https://user-images.githubusercontent.com/78332454/198849825-1fcbea97-ca31-459d-aea8-8a66b44ef214.png)
pls assign me this issue

**Comment by RIKI-05** [comment]
@AnshuPathak-88825  you can work on it

**Comment by DHRUVKHANDELWAL00** [comment]
hey @RIKI-05 , assign it to me please
