### ISSUE TITLE
FIX : Amount is not displayed instead it shows 'NaN'

### ISSUE THREAD

**Issue by ShrujanaReddy** [RIKI-05/MOMOMIA#237]
<img width="651" alt="image" src="https://github.com/RIKI-05/MOMOMIA/assets/130744023/225400f0-4945-4f30-a710-9a1c615a7720">

**Comment by ShrujanaReddy** [comment]
I would like to work on this issue. Do assign this issue to me.
Thanks!

**Comment by RIKI-05** [comment]
@ShrujanaReddy Please  fix it

**Comment by ShrujanaReddy** [comment]
@RIKI-05 Can you merge the PR as it fixes the issue.
A hacktoberfest-accepted label would be appreciated.
Thank you!
