### ISSUE TITLE
UI and UX changes

### ISSUE THREAD

**Issue by Morbius00** [RIKI-05/MOMOMIA#29]
<img src="https://img.shields.io/badge/hacktoberfest-2022-blueviolet" alt="Hacktober Badge"/>

## UI and UX changes
Hey Want to make some UI AND UX changes in your  Web- Page Home section
Please assigned me for this. I hope I will not Disappoint you
and dont forget to add the Hacktober - Fest label
Regards

**Comment by RIKI-05** [comment]
@Morbius00 please go ahead
