### ISSUE TITLE
Footer is not properly aligned

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#3]

**Comment by JawHawk** [comment]
Can you provide more information about the issue or an image of the issue ? If possible I can work on it.

**Comment by VidishaAG** [comment]
Can I be assigned? I want to work on this.

**Comment by RIKI-05** [comment]
@ JawHaw
![2022-10-09 (4)](https://user-images.githubusercontent.com/62802231/194744765-ced19e63-37b8-485d-b466-a14fddb5fb37.png)

Possibly make the  icons bigger and change the hover color of the clickable to yellow color that's used in the webpage theme

**Comment by Swap-nil-2003** [comment]
@RIKI-05 May I work on this issue?
