### ISSUE TITLE
Invert the colors of navbar 

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#40]

**Comment by Eyesnatcher-coder** [comment]
please assign me the issue

**Comment by Shivangbhatnagar237** [comment]
@RIKI-05, please assign this issue to me, and can you please explain, what do you mean by inverting, is that supposed to be a light/dark mode toggle?

**Comment by RIKI-05** [comment]
@Shivangbhatnagar237  I want the text on the navbar to be black and the navbar to be white

**Comment by Shivangbhatnagar237** [comment]
Ok, sure I'll work on this
