### ISSUE TITLE
I want to Contribute to your project by adding some cheatsheet

### ISSUE THREAD

**Issue by nihal-soni** [RIKI-05/MOMOMIA#44]
This will helpful for beginner

**Comment by RIKI-05** [comment]
What CheatSheet? Can you Explain @nihal-soni

**Comment by nihal-soni** [comment]
java , css , xml

**Comment by RIKI-05** [comment]
Sorry @nihal-soni please stick to the theme ... only the PR's related to this project is accepted

**Comment by nihal-soni** [comment]
ok
