### ISSUE TITLE
Color of social media icons in footer

### ISSUE THREAD

**Issue by AvadhootK** [RIKI-05/MOMOMIA#45]
Hey @RIKI-05 ,
The color of social media icons on the footer on hover is messed up. I think the colors of each icon should be relevant to the social media app. 
Example : red for instagram.
Can I work on this?
Also, are there any links to the social media to add there?

**Comment by RIKI-05** [comment]
@AvadhootK let the hover be yellow possibly just paste my LinkedIn link there :P

https://www.linkedin.com/in/rishika-garg05/

**Comment by AvadhootK** [comment]
Okay :)
On hover, the color of the icons is changing to blue sometimes. Do you want me to correct that so that the only hover color will be yellow? It will be consistent through all the 3 icons then
