### ISSUE TITLE
Update readme.md as per latest changes

### ISSUE THREAD

**Issue by ansharora28** [RIKI-05/MOMOMIA#49]
The homepage image has been changed,the screenshots in readme.md need to be updated as per the same. I would like to make the changes 
P.S. Can i get a URL for the snapshot to paste in readme? Since im not allowed to add assets to the repo

**Comment by RIKI-05** [comment]
https://main--momomias.netlify.app/momomia/

@ansharora28  please do the necessary changes

**Comment by pawan8120** [comment]
can I work on that issue sir

**Comment by RIKI-05** [comment]
@pawan8120  you can work on this too
