### ISSUE TITLE
Adding veg and non-veg marks in checkout modal

### ISSUE THREAD

**Issue by satyam73** [RIKI-05/MOMOMIA#53]
Hello project maintainers,
While I was scrolling through the website I noticed that when a user clicks on checkout the checkout page opens but there is no mark/symbol/logo showing for veg and non-veg which I think should be there. Please assign me this issue so I can work regarding the same.
Attaching the image for reference.
![image](https://user-images.githubusercontent.com/85296770/194772168-c0fe1cf3-7b15-4a44-a0da-71ed776e35df.png)

Thanks

**Comment by RIKI-05** [comment]
@satyam73 Please go ahead

**Comment by satyam73** [comment]
> @satyam73 Please go ahead

Hello, I have raised pull request  #125  regarding this. Please check and let me know what you think.
Thanks!
