### ISSUE TITLE
Create a Contact us Form (with Black and White Color theme)

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#61]

**Comment by Tusharjain123** [comment]
Hey @RIKI-05 Can I work on this issue?

**Comment by prateek565** [comment]
hi I would like to work on this

**Comment by RIKI-05** [comment]
@Tusharjain123 @prateek565 please go ahead

**Comment by prateek565** [comment]
HEY @RIKI-05  IS THIS OKAY ?
![Screenshot (9)](https://user-images.githubusercontent.com/78357778/194807655-27ed24e0-7066-4e16-8e20-75ff15e11bd2.png)

**Comment by RIKI-05** [comment]
@prateek565 it was supposed to be a different page...thanks for trying tho

**Comment by prateek565** [comment]
I can do it in a separate page if you want . when we click on contact us it will show
