### ISSUE TITLE
Add the provided momo gif on the left hand side of the navbar

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#64]
![monophy](https://user-images.githubusercontent.com/62802231/194799527-b9a53bb8-b6a1-4fc0-9b1a-a8ef4c3a7a21.gif)

**Comment by codewithrabeeh** [comment]
Could you assign this to me?

**Comment by RIKI-05** [comment]
@codewithrabeeh go ahead with the changes
