### ISSUE TITLE
Change the momomia text at the footer with the given image (or similarly styled text)

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#65]
![2022-10-10 (2)](https://user-images.githubusercontent.com/62802231/194800853-aacaeaad-e726-44db-90de-20f22f52c5c3.png)

you can use this image or ROBOTO font for the given text and make the background of the text block white and the font black.

**Comment by GyanPrakashRaj** [comment]
hlw, 
Kindly assign this task to me.

**Comment by RIKI-05** [comment]
@GyanPrakashRaj Please do the changes

**Comment by GyanPrakashRaj** [comment]
Did you want this change?
if you approve then ill send PR.
![omm](https://user-images.githubusercontent.com/79048275/194819996-b4883def-e892-4e48-ba9a-792a0f830e73.gif)

**Comment by RIKI-05** [comment]
@GyanPrakashRaj it's good just change the font style to Roboto

**Comment by GyanPrakashRaj** [comment]
> @GyanPrakashRaj it's good just change the font style to Roboto

resolved kindly check PR, it was assigned to me.
