### ISSUE TITLE
Enhance the UI/UX of the cart pop-pop

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#70]

**Comment by amitroy-thedev** [comment]
Hey @RIKI-05 you can assign this to me i can give it a try

**Comment by amitroy-thedev** [comment]
The project is done.. 
I could do it more better but the code was breaking hope you'll like it..

**Comment by RIKI-05** [comment]
@amitroy-thedev i opened your pr it has some conflicts fix them ill merge your pr
