### ISSUE TITLE
Add Zoom on Hover effect to the momo platter

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#72]
![2022-10-10 (4)](https://user-images.githubusercontent.com/62802231/194807624-c505216a-ea32-4e76-80e2-9e3880334974.png)

Effect to be applied on the image shown

**Comment by shivam7242** [comment]
can I work on that sir??

**Comment by 2201monesh** [comment]
Hey @RIKI-05 I would like to work on this issue, can you please assign this issue to me.

**Comment by RIKI-05** [comment]
@2201monesh  and @shivam7242  you both can work on this issue
