### ISSUE TITLE
Make the buttons on the Nav bar active for the respective section

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#74]

**Comment by AvadhootK** [comment]
Hey @RIKI-05 ,
Can I work on this task?

**Comment by Coderner** [comment]
Hey @RIKI-05, I am willing to contribute, can I work for the same?

**Comment by VineethKumarM** [comment]
Can i work on this?

**Comment by RIKI-05** [comment]
@AvadhootK  @Coderner @VineethKumarM  yall can work on it

**Comment by RIKI-05** [comment]
Hey no One's working on this ?

**Comment by VineethKumarM** [comment]
hey @RIKI-05 I am already on it and will make a pr soon. But someone already made a pr for this?😥
