### ISSUE TITLE
Change the cursor to hand pointer upon hovering over a particular category item.

### ISSUE THREAD

**Issue by Coderner** [RIKI-05/MOMOMIA#75]
Changing to hand pointer helps in differentiating an interactive element from the rest of the page. Hence this change will render a better user experience and will let user understand that there is more to clicking a particular element.

**Comment by RIKI-05** [comment]
@Coderner go ahead

**Comment by Coderner** [comment]
Please assign me for the same

**Comment by sumitbaroniya** [comment]
Please assign me this issue

**Comment by bhushan162** [comment]
can i work on this issue?
