### ISSUE TITLE
Icons not present related to the text in hygiene section

### ISSUE THREAD

**Issue by rtewari056** [RIKI-05/MOMOMIA#78]
### In the hygiene section there should be icons related to the text
![hygine](https://user-images.githubusercontent.com/75976169/194812317-50017cf0-f003-4683-b9ce-829c890ec64b.png)

**Comment by RIKI-05** [comment]
Not quite sure what you are talking about @rtewari056

**Comment by rtewari056** [comment]
#### @RIKI-05 There should be icons where the yellow tick marks present
![hygine](https://user-images.githubusercontent.com/75976169/194814261-2c50ab6a-71f6-4371-9a11-719dce1a1684.png)

**Comment by RIKI-05** [comment]
@rtewari056 leave it like that how about you just change the font color of hygiene to black

**Comment by RIKI-05** [comment]
@rtewari056 Ok go ahead with the changes
