### ISSUE TITLE
Add animation to the word inebriates 

### ISSUE THREAD

**Issue by RIKI-05** [RIKI-05/MOMOMIA#87]

**Comment by OkenHaha** [comment]
Hello, I would like to work on this, can you assign me to this?

**Comment by AmanPandagre21** [comment]
I would like to work on these can you please assign this task to me

**Comment by RIKI-05** [comment]
@OkenHaha  and @AmanPandagre21  you both can work on this

**Comment by HariPrasath-3** [comment]
can I work on this task?
