### ISSUE TITLE
Add feedback section 

### ISSUE THREAD

**Issue by Aman1143** [RIKI-05/MOMOMIA#89]
I want to add feedback section at bottom .where users can give their feedback about MOMOS.

**Comment by Aman1143** [comment]
I want to add this feature in this repo can you Allow me ??

**Comment by RIKI-05** [comment]
@Aman1143  Please go ahead

**Comment by bhushan162** [comment]
can i work on this ?

**Comment by RIKI-05** [comment]
@bhushan162 yes please go ahead

**Comment by Aman1143** [comment]
Hii @RIKI-05 I added this feature in same page but I can add this feature as link in navbar .
pls assign it me
