### ISSUE TITLE
Want to add About Us Section 

### ISSUE THREAD

**Issue by Ankit62042** [RIKI-05/MOMOMIA#9]
About us Section help users to know more about MOMOMIA and it's vision

**Comment by Ankit62042** [comment]
I would like to work on this issue

**Comment by RIKI-05** [comment]
@Ankit62042  Go ahead!

**Comment by void1244** [comment]
i want to work on this assign me

**Comment by RIKI-05** [comment]
> i want to work on this assign me

This issue already has an assignee ...please look for another issue or create your own
