### ISSUE TITLE
Mobile navbar not working 

### ISSUE THREAD

**Issue by jsvigneshkanna** [RIKI-05/MOMOMIA#91]
Description:

Mobile navbar not looking nice as expected

Screenshot:
![image](https://user-images.githubusercontent.com/42484705/194832516-8caecc74-515d-4c4c-80af-e9e30ecc9fcb.png)

Please assign this issue to my name, will work on this

**Comment by RIKI-05** [comment]
@jsvigneshkanna  please do the necessary changes

**Comment by jsvigneshkanna** [comment]
@RIKI-05 PR raised - #115
