### ISSUE TITLE
Improvement in Footer

### ISSUE THREAD

**Issue by sumitbaroniya** [RIKI-05/MOMOMIA#95]
Please assign me this issue. I would like to contribute in it under hacktoberfest.

**Comment by ItzAdarsh01** [comment]
Hello Sumit, Can you please assign me this issue. I want to contribute in it under hacktoberfest.

**Comment by ItzAdarsh01** [comment]
Hi Rishika, Can you please assign me this issue. I would like to contribute in it under hacktoberfest.

**Comment by sumitbaroniya** [comment]
Please work on another issue. I am working on this issue
