### ISSUE TITLE
Footer heading " MOMOMIA" appearing twice

### ISSUE THREAD

**Issue by Priyankar9706** [RIKI-05/MOMOMIA#97]
"MOMOMIA" is appearing twice
![Screenshot (10)](https://user-images.githubusercontent.com/84610418/194849695-92054469-9423-4309-a2d4-2509724ae416.png)

**Comment by Priyankar9706** [comment]
Please assign me the issue

**Comment by GyanPrakashRaj** [comment]
> Please assign me the issue

hi, @Priyankar9706  its becz of two merges of the same issue.
consider https://github.com/RIKI-05/MOMOMIA/pull/92 as the original.
you have to remove line no. 1273  in index.html
keep the original (line no. 1275)
 <a class="footer_clickable" href="#" font-family="Roboto" style="font-size :56px" text-style >MOMOMIA</a>
