### ISSUE TITLE
Improving responsiveness of navbar

### ISSUE THREAD

**Issue by Rashmisingh-18** [RIKI-05/MOMOMIA#99]
![MOMOMIA and 6 more pages - Personal - Microsoft​ Edge 10-10-2022 5 34 33 PM](https://user-images.githubusercontent.com/90052358/194863853-355e824d-69af-4df5-ae54-38dee69c58ca.png)

**Comment by Rashmisingh-18** [comment]
Hey @RIKI-05, can you please assign this issue to me

**Comment by RIKI-05** [comment]
@Rashmisingh-18 the issues's yours to be resolved go ahead
